### ISSUE TITLE
Which tagged version is the correct one for deployment

### ISSUE THREAD

**Issue by marceloomens** [muhammadadamfirdaus/indonesialeaks#1]
Hi @muhammadadamfirdaus,

Can you let me know which tag version in the repository is the correct one for deployment? Is it the master branch or the branch tagged "v-2"?

Thanks!

**Comment by muhammadadamfirdaus** [comment]
Hi @marceloomens,

You can use master branch for final development.
v-2 is branch for my development purposes. I always keep master clean, so you can pull on master.

Thanks.

**Comment by marceloomens** [comment]
Many thanks @muhammadadamfirdaus. Can you tell me if I should deploy the anggota.html and mitra.html files as well?

**Comment by muhammadadamfirdaus** [comment]
You're welcome @marceloomens.
I think anggota.html and mitra.html just static html files that explain who was participated. It's up to you to touch it or not.
